#
# Makefile for the fingerprint drivers.
#




obj-$(CONFIG_FINGERPRINT_GOODIX_GF32X8_QSEE)	+= goodix_3208qsee/
obj-$(CONFIG_FINGERPRINT_ELAN_96SA_QSEE)		+= elan_96sa/
obj-$(CONFIG_FINGERPRINT_ELAN_HV80SA_QSEE)		+= elan_hv80sa/
obj-$(CONFIG_FINGERPRINT_SILEAD_6163_QSEE)		+= silead_6163/
obj-$(CONFIG_FINGERPRINT_CHIPONE_7152_QSEE)		+= chipone_7152qsee/

obj-y	+=  fp_drv/
